# Database configuration for development environment
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=dev_loan_banking_system;integratedSecurity=true;encrypt=true;trustServerCertificate=true
spring.datasource.username=loan_app_user
spring.datasource.password=loanBanking@123

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true