spring.application.name=banking-system

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# create | Drops + creates tables every startup (dev only)
# create-drop | Creates on start, drops on stop (testing)
# update | Auto-alters schema (risky in prod)
# validate | Only validates schema matches entities — errors if mismatch (prod)
# none | Does nothing — you manage schema manually (enterprise prod)
# NEVER 'create-drop' in production environments, as it will lead to data loss, 'update' can be used with caution, but 'validate' or 'none' are safer choices for production
spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
# Best practice: disable OSIV in web applications, to prevent lazy loading issues and potential memory leaks
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# Spring Boot Actuator settings
management.endpoints.web.exposure.include=health,info,metrics,loggers
management.endpoint.health.show-details=when_authorized
management.endpoint.health.show-components=always
management.health.db.enabled=true
management.health.diskspace.enabled=true
management.health.ping.enabled=true
management.endpoint.health.probes.enabled=true

## Docker Environment Variables ##
#environment:
#- SPRING_PROFILES_ACTIVE=prod